
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LT = 13;
  public static final int IDENT = 17;
  public static final int PLUS = 5;
  public static final int LP = 11;
  public static final int RP = 12;
  public static final int END = 3;
  public static final int EOS = 10;
  public static final int GT = 14;
  public static final int BEGIN = 2;
  public static final int BOOLEAN = 18;
  public static final int EOF = 0;
  public static final int MULT = 7;
  public static final int NUMBER = 16;
  public static final int DIV = 8;
  public static final int MINUS = 6;
  public static final int PRINT = 4;
  public static final int error = 1;
  public static final int AVG = 9;
  public static final int EQ = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BEGIN",
  "END",
  "PRINT",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "AVG",
  "EOS",
  "LP",
  "RP",
  "LT",
  "GT",
  "EQ",
  "NUMBER",
  "IDENT",
  "BOOLEAN"
  };
}

