
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LP = 8;
  public static final int IDENT = 11;
  public static final int NUMBER = 10;
  public static final int MULT = 5;
  public static final int EOF = 0;
  public static final int PLUS = 4;
  public static final int error = 1;
  public static final int PRINT = 6;
  public static final int END = 3;
  public static final int EOS = 7;
  public static final int BEGIN = 2;
  public static final int RP = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BEGIN",
  "END",
  "PLUS",
  "MULT",
  "PRINT",
  "EOS",
  "LP",
  "RP",
  "NUMBER",
  "IDENT"
  };
}

